version: '3.5'

services:
  userserver:
    image: dulce/login-server:dev
    build:
      context: ../../
      dockerfile: Environments/Development/Server/Dockerfile

  userclient:
    image: dulce/login-client:dev
    build:
      context: ../../
      dockerfile: Environments/Development/Client/Dockerfile
